//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_commande
    {
        public int id_article { get; set; }
        public int id_commande { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
